
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterCpp.js
 */

#include "EventEmitters.h"
#include "RNOH/NativeLogger.h"


namespace facebook {
namespace react {

void MJRefreshEventEmitter::onRefresh(OnRefresh event) const {
    dispatchEvent("onRefresh", [event = std::move(event)](jsi::Runtime &runtime) {
        auto payload = jsi::Object(runtime);
        return payload;
    });
}


void MJRefreshEventEmitter::onRefreshIdle(OnRefreshIdle $event) const {
  dispatchEvent("onRefreshIdle", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    return $payload;
  });
}


void MJRefreshEventEmitter::onReleaseToRefresh(OnReleaseToRefresh $event) const {
  dispatchEvent("onReleaseToRefresh", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    return $payload;
  });
}


void MJRefreshEventEmitter::onPulling(OnPulling $event) const {
  dispatchEvent("onPulling", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    return $payload;
  });
}

} // namespace react
} // namespace facebook
