
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

class JSI_EXPORT MJRefreshEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;
    struct OnRefresh {

      };

    struct OnRefreshIdle {

      };

    struct OnReleaseToRefresh {

      };

    struct OnPulling {

      };
    void onRefresh(OnRefresh value) const;

    void onRefreshIdle(OnRefreshIdle value) const;

    void onReleaseToRefresh(OnReleaseToRefresh value) const;

    void onPulling(OnPulling value) const;
};

} // namespace react
} // namespace facebook
