
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "Props.h"
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

MJRefreshProps::MJRefreshProps(
    const PropsParserContext &context,
    const MJRefreshProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps)
      {}

} // namespace react
} // namespace facebook
